scrape_configs:
  - job_name: relay-metrics
    scrape_interval: 30s
    scrape_timeout: 7s
    metrics_path: /metrics
    sample_limit: 32
    label_limit: 8
    static_configs:
      - targets: [relay-metrics:9091]
        labels: {service: relay, environment: development, stack: relay}
